### ISSUE TITLE
Add "cache" attribute to the github_readme shortcode.

### ISSUE THREAD

**Issue by ianmjones** [octalmage/github-readme#3]
It would be good to add a cache attribute to the `github_readme` short code that works in the same way as the cache attribute does for the `github_markdown` and `github_wikipage` shortcodes.

**Comment by octalmage** [comment]
Agreed! I always meant to update it, thanks for the reminder! I'll try to check it out tonight.

**Comment by ianmjones** [comment]
It would also help with #2.

I have a PR coming your way...

**Comment by octalmage** [comment]
Even better! Thanks a ton!
